Month 7/step 1
AlexeyNewDeveloper/stellar-burgers pull request #2
Opened 2022-10-29 11:00 UTC by AlexeyNewDeveloper

2022-10-29 12:42 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- Убрать синюю обводку у блоков, эта обводка на макете нужна только что бы сделать описание поясняющее к этому блоку;

- Не нужно задавать активность элементов в шапке через стейт;

- Во всём проекте, для всех компонентов, где используются пропсы, нужно описать propTypes. Также в описании propTypes компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается. Не забудьте перед отправкой работы проверить консоль в браузере (F12) на наличие ошибок.

- По чек-листу, компонент list-order должен называться BurgerConstructor.

- Старайтесь не дробить сильно компоненты, если этого не требует ситуация. Описал пример в `burger-ingredients`.

### **Сделает код лучше:**

- используйте функциональные компоненты, а не классовые

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +        };
**Надо исправить:** 

В шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать через стейт

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +class AppHeader extends React.Component {
**Можно лучше:** 

Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/menu-item/menu-item.jsx
> +    }
**Надо исправить:** 

В шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать через стейт

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                />
**Можно лучше:** Тут не будет никакой логики, поэтому не стоит дробить хедер на отдельные компоненты.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/content/content.jsx
> +    };
**Можно лучше:** Тут больше подойдет метод reduce. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/content/content.jsx
> +export default class Content extends React.Component {
**Надо испарвить**

Для этого компонента так же нужно описать PropTypes

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +export default class BurgerIngredients extends React.Component {
**Надо испарвить**

Для этого компонента так же нужно описать PropTypes

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/ingredients-wrapper/ingredients-wrapper.jsx
> +export default class IngredientsWrapper extends React.Component {
**Надо исправить:** не стоит так сильно дробить компоненты. Тут нету сложной логики, поэтому лучше не выносить этот участок кода в отдельный компонент.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/item-card/item-card.jsx
> +                )}
**Можно лучше:** тут можно у всех вывести Couter, этот функционал вы будете реализовывать через спринт.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/place-order/place-order.jsx
> +export default class PlaceOrder extends React.Component {
**Надо исправить:** Похожее замечание описал в компоненте - IngredientsWrapper.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/title-element/title-element.jsx
> +export default class TitleElement extends React.Component {
**Надо исправить:** Похожее замечание описал в компоненте - IngredientsWrapper.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/tabs/tabs.jsx
> +        <div style={{ display: "flex" }} className="mb-10">
**Надо исправить:** 

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. Проверьте во всём проекте.

2022-10-29 12:42 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    <IngredientsWrapper data={this.props.data.bun} />
**Можно лучше**

У каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его.

2022-11-01 13:07 UTC, AlexeyNewDeveloper commented on src/components/app-header/app-header.jsx
> +        };
Стейт убрал

2022-11-03 04:20 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Практически все замечания с прошлого ревью были исправлены.

### **Вы молодец! Приступайте к финальной части работы.**

### **Но есть несколько замечаний, которые нужно исправить:**

- Необходимо полное описание структуры, а не PropTypes.object или PropTypes.array, так же необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

- Поправьте логику работы с Popup. Логика по закрытию попапа на нажатие клавиши `Esc` должна находиться в самом компоненте Popup.

- По чек-листу у вас должен быть компонент PopupOverlay.

- Исправить работу с данными. Не нужно проводить различные преобразования и разбиение моковых данных.

### **Сделает код лучше:**

- используйте функциональные компоненты, а не классовые, сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/menu-item/menu-item.jsx
> +        ref={this.ref}
**Надо исправить:** Тут не нужен ref. Мы не выполняем никаких действий с ссылками.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/menu-item/menu-item.jsx
> +    };
**Надо исправить:** Делайте вывод в jsx. Передавайте иконки через пропсы.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +              <li
**Надо исправить:** Здесь и далее. Вы должны использовать вывод через цикл, на данном этапе, используя моковые данные, а в финальной части, нужно использовать данные с сервера.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +        )}
**Можно лучше:** попап можно занести в `section`. Это никак не повлияет на структуру.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      },
**Можно лучше:** Лучше вынести в константу.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +              <React.Fragment key={index}>
**Надо исправить:** Здесь не нужен React Fragment.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/content/content.jsx
> +  data: PropTypes.arrayOf(PropTypes.object).isRequired,
**Надо исправить:**

Во всём проекте.
Необходимо полное описание структуры, а не PropTypes.object или PropTypes.array, так же необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/ingredients-category/ingredients-category.jsx
> +                  detailDataForPopup={this.props.arrayOfDetailDataForPopup.find(
**Надо исправить:** Зачему тут дополнительно что-то искать, если у нас итак `item` есть.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/content/content.jsx
> +      detailDataForPopup: { bun: [], sauce: [], main: [] },
**Надо исправить:** Нужно убрать связанную с этим полем логику. У нас уже есть все даннные для того чтобы корректно выводить попап.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/content/content.jsx
> +      mainData: { bun: [], sauce: [], main: [] },
**надо исправить:** Лучше в самом компоненте BurgerIngredients, в методе render делать фильтрацию.

```js
  const buns = ingredients.filter((item) => item.type === "bun");

  const mains = ingredients.filter((item) => item.type === "main");

  const sauces = ingredients.filter((item) => item.type === "sauce");
```

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/content/content.jsx
> +
**Надо исправить:** Вам не нужно никак преобразовывать данные. Они должны быть такими какими были изначально. Поэтому можно сразу использовать моковые даные. В финальной части задания вам нужно будет получать и использовать, только данные с сервера.

2022-11-03 04:20 UTC, ArslanMustafin commented on src/components/popup-for-ingredient-info/popup-for-ingredient-info.jsx
> +      },
**Надо исправить:** Не стоит выносить эти данные в локальный стейт, лучше вынести в константу.

2022-11-03 04:20 UTC, ArslanDev666 commented on src/components/popup-for-ingredient-info/popup-for-ingredient-info.jsx
> +  };
**надо исправить:** Логика закрытия попапа, должна быть в компоненте Popup.

2022-11-03 04:20 UTC, ArslanDev666 commented on src/components/popup-for-ingredient-info/popup-for-ingredient-info.jsx
> +  };
**Надо исправить:** Тут лучше не делать ещё 1 обработчик событий. Достаточно просто повесить обработчик закрытия попапа, на onClick в ModalOverlay.

Примерная структура компонента Popup:

```js
<>
  <div className={styles.modal}>{/** ...контент попапа */}</div>
  <ModalOverlay onClick={onClose} />
</>
```

2022-11-03 04:20 UTC, ArslanDev666 commented on src/components/tabs/tabs.jsx
> +  const [current, setCurrent] = React.useState("bulki");
**Надо исправить:** Измените значения в useState на английское. Не стоит использовать транслит.

2022-11-10 18:13 UTC, closed without merging